"use client";

import { useState } from "react";
import { baseProducts, combos, seasonalPacks, subscriptionPlans } from "@/lib/catalog/data";

const categoryImages: Record<string, string> = { "Almendras": "/images/almonds-front.png", "Chía": "/images/seeds-category.png", "Avena": "/images/flours-category.png", "Granola": "/images/snacks-category.png" };
const featured = combos.filter((combo) => combo.featured);

export default function Home() {
  const [cartCount, setCartCount] = useState(0);
  return <main>
    <a className="skip" href="#contenido">Saltar al contenido</a>
    <div className="topbar">Seleccionado y preparado en Los Perales, San Salvador de Jujuy <span>•</span> Retiro disponible y entregas locales</div>
    <header className="header"><a className="brand" href="#inicio"><span>SV</span> saludablemente<br />vivo</a><nav aria-label="Navegación principal"><a href="#tienda">Tienda</a><a href="#combos">Combos</a><a href="#suscripciones">Suscripciones</a><a href="#beneficios">Beneficios</a></nav><button className="cart" aria-label={`Abrir carrito con ${cartCount} productos`}>Bolsa <b>{cartCount}</b></button></header>
    <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">ALIMENTOS REALES, ELEGIDOS CON CUIDADO</p><h1>Comé mejor.<br /><em>Nosotros hacemos<br />el resto.</em></h1><p className="lead">Tu despensa saludable, seleccionada, envasada al vacío y preparada desde Los Perales.</p><div className="hero-actions"><a className="button primary" href="#combos">Elegí un combo <span>→</span></a><a className="button secondary" href="#tienda">Comprar productos</a></div></div><div className="hero-image" role="img" aria-label="Selección de alimentos saludables envasados al vacío"><div className="hero-photo" /></div></section>
    <section className="assurances" aria-label="Beneficios"><div className="assurance"><i>⌂</i><div><strong>Retiro en Los Perales</strong><span>Cuando te quede cómodo</span></div></div><div className="assurance"><i>↗</i><div><strong>Entrega local</strong><span>San Salvador de Jujuy</span></div></div><div className="assurance"><i>✦</i><div><strong>Sellado al vacío</strong><span>Frescura que se nota</span></div></div><div className="assurance"><i>✓</i><div><strong>15 productos, muchas opciones</strong><span>Menos stock, mejor selección</span></div></div></section>
    <section className="section decision-paths" id="contenido"><p className="eyebrow">ELEGÍ COMO TE RESULTE MÁS FÁCIL</p><h2>No necesitás saber<br /><em>exactamente qué comprar.</em></h2><div className="path-grid"><a href="#tienda"><b>01</b><h3>Comprar productos</h3><p>Para quien ya sabe qué está buscando.</p><span>Ver los 15 productos →</span></a><a href="#combos"><b>02</b><h3>Elegí un combo</h3><p>Una selección lista para tu objetivo.</p><span>Encontrar el mío →</span></a><a href="#suscripciones"><b>03</b><h3>Recibí todos los meses</h3><p>Tu despensa se repone sola cada 30 días.</p><span>Ver planes →</span></a><a href="#beneficios"><b>04</b><h3>Sumá beneficios</h3><p>Puntos, referidos y packs de temporada.</p><span>Conocer beneficios →</span></a></div></section>
    <section className="section products" id="tienda"><div className="section-heading"><div><p className="eyebrow">LOS 15 ESENCIALES</p><h2>Todo lo bueno,<br />sin complicarlo.</h2></div><p className="section-text">El catálogo inicial crece desde una selección clara, fresca y versátil.</p></div><div className="base-product-grid">{baseProducts.map(([slug, name, weight], index) => <article className="base-product" key={slug}><img src={categoryImages[name] ?? "/images/hero-premium-food.png"} alt={name} /><div><p>{weight}</p><h3>{name}</h3><span>Desde</span><button onClick={() => setCartCount((count) => count + 1)} aria-label={`Agregar ${name} a la bolsa`}>Agregar <b>+</b></button></div></article>)}</div></section>
    <section className="section featured-combos" id="combos"><div className="section-heading"><div><p className="eyebrow">COMBOS DESTACADOS</p><h2>Elegidos para tu<br /><em>momento del día.</em></h2></div><a className="text-link" href="/combos">Ver los 22 combos <span>→</span></a></div><div className="offer-grid">{featured.map((combo, index) => <article className="offer-card" key={combo.name}><img src={index === 1 ? "/images/combo-fitness.png" : "/images/hero-premium-food.png"} alt="" /><div className="offer-content"><p className="eyebrow">{combo.group.toUpperCase()}</p><h3>{combo.name}</h3><p>{combo.purpose}</p><ul>{combo.items.map((item) => <li key={item}>{item}</li>)}</ul><div className="offer-footer"><span>Ahorrás {combo.discount}%</span><button onClick={() => setCartCount((count) => count + 1)}>Elegir combo →</button></div></div></article>)}</div></section>
    <section className="profiles"><div><p className="eyebrow">ELEGÍ SEGÚN VOS</p><h2>Una buena elección<br />empieza por entender<br /><em>tu rutina.</em></h2></div><div className="profile-links">{[["Para desayunos", "Avena, granola, miel y semillas."],["Para entrenar", "Energía real antes y después."],["Para estudiar", "Snacks para acompañar el foco."],["Para la familia", "Más cantidad, más tranquilidad."],["Para regalar", "Cajas con buena intención."]].map(([title, detail]) => <a href="#combos" key={title}><h3>{title}</h3><p>{detail}</p><span>Explorar →</span></a>)}</div></section>
    <section className="subscription" id="suscripciones"><div><p className="eyebrow">CADA 30 DÍAS</p><h2>Tu despensa,<br /><em>siempre completa.</em></h2><p>Elegí un plan, recibí tus favoritos todos los meses y pausá o cancelá cuando quieras.</p><a className="button light" href="/suscripciones">Ver todos los planes <span>→</span></a></div><div className="plan-stack">{subscriptionPlans.slice(0, 3).map(([name, purpose, items, benefit]) => <article key={name}><span>{name === "Esencial" ? "MÁS ELEGIDO" : "MENSUAL"}</span><h3>Plan {name}</h3><p>{purpose}</p><small>{items.join(" · ")}</small><strong>{benefit}</strong></article>)}</div></section>
    <section className="section benefits" id="beneficios"><div className="section-heading"><div><p className="eyebrow">BENEFICIOS QUE VUELVEN</p><h2>Comer mejor también<br />puede darte más.</h2></div></div><div className="benefit-grid"><article><b>01</b><h3>Sumá puntos</h3><p>1 punto por cada $1.000 de compra aprobada.</p><span>50 puntos = 5% OFF</span></article><article><b>02</b><h3>Canjeá cuando quieras</h3><p>100 puntos = envío gratis. 200 puntos = Mix Premium de regalo.</p><span>Sujeto a stock</span></article><article><b>03</b><h3>Invitá a alguien</h3><p>Tu amigo recibe bienvenida; vos sumás puntos cuando hace su primera compra.</p><span>Beneficio para ambos</span></article></div></section>
    <section className="seasonal"><p className="eyebrow">PACKS QUE CAMBIAN CON LA TEMPORADA</p><h2>Siempre hay una<br /><em>buena excusa para elegirte.</em></h2><div>{seasonalPacks.map((pack) => <span key={pack}>{pack}</span>)}</div><a className="button primary" href="/promos">Ver promociones <span>→</span></a></section>
    <footer><a className="brand" href="#inicio"><span>SV</span> saludablemente<br />vivo</a><p>Alimentos reales para una vida más liviana.</p><div className="footer-links"><a href="#tienda">Tienda</a><a href="#suscripciones">Suscripciones</a><a href="#beneficios">Beneficios</a></div><small>© 2026 Saludablemente Vivo · Hecho con cuidado en Los Perales, San Salvador de Jujuy</small></footer>
  </main>;
}
