"use client";
import { useMemo, useRef, useState, useTransition } from "react";
import { useCart } from "@/app/cart-provider";
import { requestOtp, verifyOtp } from "@/app/(auth)/ingresar/actions";
import { createCheckoutOrder, createPaymentPreference } from "./actions";

type Slot = { id: string; starts_at: string; ends_at: string; zone_id: string; delivery_zones: { name: string; estimated_minutes: number } | null };
export function CheckoutClient({ slots }: { slots: Slot[] }) {
  const { items, couponCode, setCoupon } = useCart(); const [pending, startTransition] = useTransition(); const checkoutKey = useRef(crypto.randomUUID());
  const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [otpSent, setOtpSent] = useState(false); const [authenticated, setAuthenticated] = useState(false); const [error, setError] = useState(""); const [fulfillment, setFulfillment] = useState<"delivery" | "pickup">("delivery"); const [slotId, setSlotId] = useState(""); const [scheduledFor, setScheduledFor] = useState("");
  const subtotal = useMemo(() => items.reduce((sum, item) => sum + (item.estimatedUnitPrice ?? 0) * item.quantity, 0), [items]);
  function sendOtp() { startTransition(async () => { try { await requestOtp(email); setOtpSent(true); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo enviar el código."); } }); }
  function confirmOtp() { startTransition(async () => { try { await verifyOtp(email, code); setAuthenticated(true); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Código inválido."); } }); }
  function pay(fd: FormData) { startTransition(async () => { try { const order = await createCheckoutOrder({ items: items.map(({ kind, id, quantity }) => ({ kind, id, quantity })), couponCode, fulfillment, deliverySlotRuleId: fulfillment === "delivery" ? slotId : undefined, scheduledFor: fulfillment === "delivery" ? new Date(scheduledFor).toISOString() : undefined, idempotencyKey: checkoutKey.current, address: fulfillment === "delivery" ? { label: "Casa", recipientName: String(fd.get("recipientName")), phone: String(fd.get("phone")), street: String(fd.get("street")), number: String(fd.get("number")), floor: String(fd.get("floor") || ""), apartment: String(fd.get("apartment") || ""), city: String(fd.get("city")), province: String(fd.get("province")), postalCode: String(fd.get("postalCode")), saveAsDefault: Boolean(fd.get("saveDefault")) } : undefined }); const preference = await createPaymentPreference(order.order_id); window.location.assign(preference.initPoint); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo iniciar el pago."); } }); }
  if (!items.length) return <main className="section"><h1>Tu bolsa está vacía.</h1><a className="button primary" href="/tienda">Ir a la tienda</a></main>;
  return <main className="section checkout"><p className="eyebrow">CHECKOUT SEGURO</p><h1>Finalizá tu compra.</h1><ol className="checkout-steps"><li>Resumen</li><li>Contacto</li><li>Entrega</li><li>Pago</li></ol><form action={(form) => pay(form)}>
    <section><h2>1. Tu pedido</h2><ul>{items.map((item) => <li key={`${item.kind}-${item.id}`}>{item.quantity} × {item.name}</li>)}</ul><p>Subtotal estimado: ${subtotal.toLocaleString("es-AR") || "a confirmar"}</p><label>Cupón <input defaultValue={couponCode} onChange={(event) => setCoupon(event.target.value)} /></label></section>
    <section><h2>2. Contacto</h2><label>Email <input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label>{!otpSent ? <button type="button" onClick={sendOtp} disabled={pending}>Enviar código</button> : <><label>Código de 6 dígitos <input inputMode="numeric" value={code} onChange={(event) => setCode(event.target.value)} /></label><button type="button" onClick={confirmOtp} disabled={pending}>Verificar email</button></>} {authenticated && <p role="status">Email verificado.</p>}</section>
    <section><h2>3. ¿Cómo lo recibís?</h2><label><input type="radio" checked={fulfillment === "delivery"} onChange={() => setFulfillment("delivery")} /> Delivery en San Salvador de Jujuy</label><label><input type="radio" checked={fulfillment === "pickup"} onChange={() => setFulfillment("pickup")} /> Retiro en Los Perales</label>{fulfillment === "pickup" ? <p>Te avisaremos cuándo retirar tu pedido en Los Perales.</p> : <><label>Nombre y apellido <input name="recipientName" required /></label><label>Teléfono <input name="phone" inputMode="tel" required /></label><label>Calle <input name="street" required /></label><label>Altura <input name="number" required /></label><label>Piso <input name="floor" /></label><label>Departamento <input name="apartment" /></label><label>Ciudad <input name="city" defaultValue="San Salvador de Jujuy" required /></label><label>Provincia <input name="province" defaultValue="Jujuy" required /></label><label>Código postal <input name="postalCode" required /></label><label>Franja <select value={slotId} onChange={(event) => setSlotId(event.target.value)} required><option value="">Elegí una franja</option>{slots.map((slot) => <option key={slot.id} value={slot.id}>{slot.delivery_zones?.name}: {slot.starts_at.slice(0,5)}–{slot.ends_at.slice(0,5)}</option>)}</select></label><label>Fecha y hora de inicio <input type="datetime-local" value={scheduledFor} onChange={(event) => setScheduledFor(event.target.value)} required /></label><label><input type="checkbox" name="saveDefault" /> Guardar como dirección predeterminada</label></>}</section>
    {error && <p role="alert">{error}</p>}<button className="button primary" disabled={!authenticated || pending} type="submit">{pending ? "Procesando…" : "Ir a Mercado Pago"}</button>
  </form></main>;
}
