-- Saludablemente Vivo: transactional schema. Apply with `supabase db push`.
create extension if not exists pgcrypto;
create extension if not exists citext;

create type public.order_status as enum ('draft','pending_payment','paid','preparing','ready','shipped','delivered','cancelled','refunded');
create type public.payment_status as enum ('pending','authorized','approved','rejected','cancelled','refunded','failed');
create type public.subscription_status as enum ('active','paused','cancelled','expired');
create type public.fulfillment_type as enum ('delivery','pickup');

create function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

create table public.roles (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.permissions (id uuid primary key default gen_random_uuid(), code text unique not null, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.role_permissions (role_id uuid references public.roles(id) on delete cascade, permission_id uuid references public.permissions(id) on delete cascade, primary key(role_id,permission_id));
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email citext unique not null, full_name text, phone text, avatar_url text, points integer not null default 0 check(points >= 0), deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (user_id uuid references public.profiles(id) on delete cascade, role_id uuid references public.roles(id) on delete cascade, primary key(user_id,role_id));

create table public.brands (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, logo_path text, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), parent_id uuid references public.categories(id), name text not null, slug text unique not null, description text, image_path text, sort_order integer not null default 0, is_active boolean not null default true, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), brand_id uuid references public.brands(id), category_id uuid references public.categories(id), name text not null, slug text unique not null, sku text unique not null, internal_code text unique, qr_code text unique, short_description text, description text, ingredients text, allergens text, nutritional_info jsonb not null default '{}'::jsonb, weight_grams integer check(weight_grams > 0), price numeric(12,2) not null check(price >= 0), sale_price numeric(12,2) check(sale_price >= 0), cost numeric(12,2) check(cost >= 0), margin numeric(5,2) generated always as (case when price > 0 and cost is not null then round(((price-cost)/price)*100,2) else null end) stored, stock integer not null default 0 check(stock >= 0), min_stock integer not null default 0 check(min_stock >= 0), batch_number text, packed_at date, expires_at date, status text not null default 'draft' check(status in ('draft','active','archived')), search_document tsvector generated always as (to_tsvector('spanish', coalesce(name,'') || ' ' || coalesce(short_description,''))) stored, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, storage_path text not null, alt_text text not null, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_tags (product_id uuid references public.products(id) on delete cascade, tag text not null, primary key(product_id,tag));
create table public.inventory (id uuid primary key default gen_random_uuid(), product_id uuid unique not null references public.products(id) on delete cascade, warehouse_code text not null default 'MAIN', quantity integer not null default 0 check(quantity >= 0), reserved_quantity integer not null default 0 check(reserved_quantity >= 0), reorder_point integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.inventory_movements (id uuid primary key default gen_random_uuid(), inventory_id uuid not null references public.inventory(id), order_id uuid, movement_type text not null check(movement_type in ('in','out','adjustment','reserve','release')), quantity integer not null check(quantity <> 0), reason text, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());

create table public.combos (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, image_path text, discount_percent numeric(5,2) not null default 0 check(discount_percent between 0 and 100), is_active boolean not null default true, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.combo_items (combo_id uuid references public.combos(id) on delete cascade, product_id uuid references public.products(id), quantity integer not null check(quantity > 0), primary key(combo_id,product_id));
create table public.kits (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, image_path text, discount_percent numeric(5,2) not null default 0 check(discount_percent between 0 and 100), is_customizable boolean not null default true, is_active boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.kit_items (kit_id uuid references public.kits(id) on delete cascade, product_id uuid references public.products(id), quantity integer not null check(quantity > 0), primary key(kit_id,product_id));

create table public.addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, label text not null, recipient_name text not null, phone text not null, street text not null, number text not null, floor text, apartment text, city text not null, province text not null, postal_code text not null, latitude numeric(10,7), longitude numeric(10,7), is_default boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.delivery_zones (id uuid primary key default gen_random_uuid(), name text unique not null, polygon jsonb, estimated_minutes integer not null check(estimated_minutes > 0), is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.shipping_rules (id uuid primary key default gen_random_uuid(), zone_id uuid references public.delivery_zones(id) on delete cascade, minimum_order numeric(12,2) not null default 0, fee numeric(12,2) not null check(fee >= 0), free_shipping_threshold numeric(12,2), fulfillment fulfillment_type not null default 'delivery', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.coupons (id uuid primary key default gen_random_uuid(), code citext unique not null, description text, discount_type text not null check(discount_type in ('percent','fixed')), discount_value numeric(12,2) not null check(discount_value > 0), minimum_order numeric(12,2) not null default 0, starts_at timestamptz, ends_at timestamptz, max_redemptions integer, redemption_count integer not null default 0, is_active boolean not null default true, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.orders (id uuid primary key default gen_random_uuid(), order_number bigint generated always as identity unique, user_id uuid references public.profiles(id), address_id uuid references public.addresses(id), coupon_id uuid references public.coupons(id), status public.order_status not null default 'draft', fulfillment public.fulfillment_type not null, delivery_zone_id uuid references public.delivery_zones(id), scheduled_for timestamptz, subtotal numeric(12,2) not null check(subtotal >= 0), discount_total numeric(12,2) not null default 0 check(discount_total >= 0), shipping_total numeric(12,2) not null default 0 check(shipping_total >= 0), total numeric(12,2) not null check(total >= 0), currency char(3) not null default 'ARS', notes text, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id), name_snapshot text not null, sku_snapshot text, unit_price numeric(12,2) not null check(unit_price >= 0), quantity integer not null check(quantity > 0), discount_total numeric(12,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id), provider text not null default 'mercadopago', provider_payment_id text unique, status public.payment_status not null default 'pending', amount numeric(12,2) not null check(amount >= 0), currency char(3) not null default 'ARS', raw_response jsonb, paid_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payment_attempts (id uuid primary key default gen_random_uuid(), payment_id uuid not null references public.payments(id) on delete cascade, idempotency_key uuid not null default gen_random_uuid(), request_payload jsonb, response_payload jsonb, status public.payment_status not null, created_at timestamptz not null default now(), unique(payment_id,idempotency_key));

create table public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), address_id uuid references public.addresses(id), status public.subscription_status not null default 'active', interval_days integer not null check(interval_days in (15,30,60)), next_charge_at timestamptz not null, discount_percent numeric(5,2) not null default 0, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.subscription_items (subscription_id uuid references public.subscriptions(id) on delete cascade, product_id uuid references public.products(id), quantity integer not null check(quantity > 0), primary key(subscription_id,product_id));
create table public.favorites (user_id uuid references public.profiles(id) on delete cascade, product_id uuid references public.products(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,product_id));
create table public.wishlists (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, name text not null default 'Mi lista', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.wishlist_items (wishlist_id uuid references public.wishlists(id) on delete cascade, product_id uuid references public.products(id), created_at timestamptz not null default now(), primary key(wishlist_id,product_id));
create table public.reviews (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), product_id uuid not null references public.products(id), order_item_id uuid references public.order_items(id), rating smallint not null check(rating between 1 and 5), body text, is_published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,product_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, type text not null, title text not null, body text, read_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.banners (id uuid primary key default gen_random_uuid(), title text not null, image_path text not null, href text, starts_at timestamptz, ends_at timestamptz, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.settings (key text primary key, value jsonb not null, updated_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.otp_requests (id uuid primary key default gen_random_uuid(), email citext not null, ip_address text not null, expires_at timestamptz not null, verified_at timestamptz, created_at timestamptz not null default now());
create table public.email_logs (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id), recipient citext not null, template text not null, provider_id text, status text not null default 'queued', metadata jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.inventory_movements add constraint inventory_movements_order_id_fkey foreign key(order_id) references public.orders(id);

create index products_category_active_idx on public.products(category_id) where deleted_at is null and status = 'active';
create index products_search_idx on public.products using gin(search_document); create index product_images_product_idx on public.product_images(product_id,sort_order); create index orders_user_created_idx on public.orders(user_id,created_at desc); create index orders_status_created_idx on public.orders(status,created_at desc); create index payments_order_idx on public.payments(order_id); create index inventory_low_stock_idx on public.inventory(product_id) where quantity <= reorder_point; create index subscriptions_due_idx on public.subscriptions(next_charge_at) where status = 'active'; create index notifications_unread_idx on public.notifications(user_id,created_at desc) where read_at is null; create index otp_rate_limit_idx on public.otp_requests(email,ip_address,created_at desc); create index audit_entity_idx on public.audit_logs(entity_type,entity_id,created_at desc);

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=auth.uid() and r.code in ('admin','employee','preparer','driver')) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,email) values(new.id,new.email) on conflict(id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

insert into public.roles(code,name) values ('admin','Administrador'),('employee','Empleado'),('preparer','Preparador'),('driver','Repartidor'),('customer','Cliente') on conflict(code) do nothing;

-- Every exposed table has RLS. Public catalog data is read-only; private data is owner-only; staff uses the role helper.
alter table public.profiles enable row level security; alter table public.addresses enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.payments enable row level security; alter table public.subscriptions enable row level security; alter table public.notifications enable row level security; alter table public.favorites enable row level security; alter table public.wishlists enable row level security; alter table public.wishlist_items enable row level security; alter table public.reviews enable row level security;
create policy "profiles_owner" on public.profiles for all using (id=auth.uid() or public.is_staff()) with check (id=auth.uid() or public.is_staff());
create policy "addresses_owner" on public.addresses for all using (user_id=auth.uid() or public.is_staff()) with check (user_id=auth.uid() or public.is_staff());
create policy "orders_owner" on public.orders for select using (user_id=auth.uid() or public.is_staff()); create policy "order_items_owner" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_staff())));
create policy "payments_owner" on public.payments for select using (exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_staff())));
create policy "subscriptions_owner" on public.subscriptions for all using (user_id=auth.uid() or public.is_staff()) with check (user_id=auth.uid() or public.is_staff()); create policy "notifications_owner" on public.notifications for all using (user_id=auth.uid() or public.is_staff()) with check (user_id=auth.uid() or public.is_staff());
create policy "favorites_owner" on public.favorites for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy "wishlists_owner" on public.wishlists for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy "wishlist_items_owner" on public.wishlist_items for all using (exists(select 1 from public.wishlists w where w.id=wishlist_id and w.user_id=auth.uid())) with check (exists(select 1 from public.wishlists w where w.id=wishlist_id and w.user_id=auth.uid()));
create policy "reviews_read_published" on public.reviews for select using (is_published or user_id=auth.uid() or public.is_staff()); create policy "reviews_owner_insert" on public.reviews for insert with check (user_id=auth.uid()); create policy "reviews_owner_update" on public.reviews for update using (user_id=auth.uid() or public.is_staff());
alter table public.products enable row level security; alter table public.categories enable row level security; alter table public.brands enable row level security; alter table public.product_images enable row level security; alter table public.combos enable row level security; alter table public.combo_items enable row level security; alter table public.kits enable row level security; alter table public.kit_items enable row level security; alter table public.banners enable row level security; alter table public.delivery_zones enable row level security; alter table public.shipping_rules enable row level security;
create policy "catalog_read_products" on public.products for select using (status='active' and deleted_at is null or public.is_staff()); create policy "catalog_read_categories" on public.categories for select using (is_active and deleted_at is null or public.is_staff()); create policy "catalog_read_brands" on public.brands for select using (deleted_at is null or public.is_staff()); create policy "catalog_read_images" on public.product_images for select using (true); create policy "catalog_read_combos" on public.combos for select using (is_active and deleted_at is null or public.is_staff()); create policy "catalog_read_combo_items" on public.combo_items for select using (true); create policy "catalog_read_kits" on public.kits for select using (is_active and deleted_at is null or public.is_staff()); create policy "catalog_read_kit_items" on public.kit_items for select using (true); create policy "catalog_read_banners" on public.banners for select using (is_active); create policy "catalog_read_delivery_zones" on public.delivery_zones for select using (is_active); create policy "catalog_read_shipping_rules" on public.shipping_rules for select using (is_active);

do $$ declare table_name text; begin for table_name in select unnest(array['roles','permissions','role_permissions','user_roles','inventory','inventory_movements','coupons','payment_attempts','settings','otp_requests','email_logs','audit_logs']) loop execute format('alter table public.%I enable row level security',table_name); execute format('create policy staff_only on public.%I for all using (public.is_staff()) with check (public.is_staff())',table_name); end loop; end $$;
do $$ declare table_name text; begin for table_name in select unnest(array['roles','permissions','profiles','brands','categories','products','product_images','inventory','combos','kits','addresses','delivery_zones','shipping_rules','coupons','orders','order_items','payments','subscriptions','reviews','wishlists','notifications','banners','settings','email_logs']) loop execute format('create trigger set_%I_updated_at before update on public.%I for each row execute procedure public.set_updated_at()',table_name,table_name); end loop; end $$;
