-- Lean catalog, subscriptions and loyalty. All commercial values derive from product data.
create type public.collection_kind as enum ('profile','seasonal_pack');
create type public.plan_mode as enum ('fixed','customizable');
create type public.loyalty_event as enum ('purchase','refund','redemption','referral','manual_adjustment');
create type public.referral_status as enum ('pending','qualified','rewarded','cancelled');

alter table public.combos add column if not exists audience text, add column if not exists objective text, add column if not exists badge text, add column if not exists is_featured boolean not null default false, add column if not exists starts_at timestamptz, add column if not exists ends_at timestamptz;
alter table public.kits add column if not exists audience text, add column if not exists objective text, add column if not exists badge text, add column if not exists starts_at timestamptz, add column if not exists ends_at timestamptz;

create table public.subscription_plans (
  id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, mode public.plan_mode not null default 'fixed', interval_days integer not null default 30 check(interval_days = 30), discount_percent numeric(5,2) not null default 0 check(discount_percent between 0 and 100), minimum_items smallint, maximum_items smallint, is_active boolean not null default true, is_featured boolean not null default false, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check((mode='fixed' and minimum_items is null and maximum_items is null) or (mode='customizable' and minimum_items > 0 and maximum_items >= minimum_items))
);
create table public.subscription_plan_items (plan_id uuid not null references public.subscription_plans(id) on delete cascade, product_id uuid not null references public.products(id), quantity integer not null check(quantity > 0), primary key(plan_id, product_id));
alter table public.subscriptions add column if not exists plan_id uuid references public.subscription_plans(id), add column if not exists provider_preapproval_id text unique, add column if not exists next_retry_at timestamptz, add column if not exists failure_count integer not null default 0;
create table public.subscription_charge_attempts (id uuid primary key default gen_random_uuid(), subscription_id uuid not null references public.subscriptions(id) on delete cascade, provider_payment_id text unique, status public.payment_status not null, attempted_at timestamptz not null default now(), response_payload jsonb);

create table public.catalog_collections (id uuid primary key default gen_random_uuid(), kind public.collection_kind not null, slug text unique not null, name text not null, description text, image_path text, starts_at timestamptz, ends_at timestamptz, is_active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(kind='profile' or (starts_at is not null and ends_at is not null and ends_at > starts_at)));
create table public.catalog_collection_items (id uuid primary key default gen_random_uuid(), collection_id uuid not null references public.catalog_collections(id) on delete cascade, product_id uuid references public.products(id), combo_id uuid references public.combos(id), subscription_plan_id uuid references public.subscription_plans(id), sort_order integer not null default 0, created_at timestamptz not null default now(), check(num_nonnulls(product_id, combo_id, subscription_plan_id)=1));

create table public.loyalty_ledger (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), event public.loyalty_event not null, points integer not null check(points <> 0), order_id uuid references public.orders(id), expires_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.loyalty_rewards (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, points_cost integer not null check(points_cost > 0), reward_type text not null check(reward_type in ('discount_percent','free_shipping','gift_product')), discount_percent numeric(5,2), product_id uuid references public.products(id), is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check((reward_type='discount_percent' and discount_percent is not null) or (reward_type='gift_product' and product_id is not null) or reward_type='free_shipping'));
create table public.referral_codes (id uuid primary key default gen_random_uuid(), user_id uuid unique not null references public.profiles(id), code citext unique not null, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.referral_rewards (id uuid primary key default gen_random_uuid(), referral_code_id uuid not null references public.referral_codes(id), referred_user_id uuid not null unique references public.profiles(id), first_order_id uuid unique references public.orders(id), status public.referral_status not null default 'pending', inviter_points integer not null default 50 check(inviter_points > 0), welcome_discount_percent numeric(5,2) not null default 5 check(welcome_discount_percent between 0 and 100), rewarded_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create view public.combo_availability with (security_invoker=true) as
select c.id, c.slug, c.name, greatest(0, min(floor(p.stock::numeric / ci.quantity)))::integer as available_stock,
sum(coalesce(p.sale_price,p.price) * ci.quantity) as individual_price,
round(sum(coalesce(p.sale_price,p.price) * ci.quantity) * (1-c.discount_percent/100),2) as combo_price,
round(sum(coalesce(p.sale_price,p.price) * ci.quantity) * c.discount_percent/100,2) as savings
from public.combos c join public.combo_items ci on ci.combo_id=c.id join public.products p on p.id=ci.product_id
where c.is_active and c.deleted_at is null and p.status='active' and p.deleted_at is null and (c.starts_at is null or c.starts_at <= now()) and (c.ends_at is null or c.ends_at > now())
group by c.id;

create index subscription_plans_active_idx on public.subscription_plans(sort_order) where is_active; create index collections_active_idx on public.catalog_collections(kind,sort_order) where is_active; create index collection_items_unique_idx on public.catalog_collection_items(collection_id,coalesce(product_id,combo_id,subscription_plan_id)); create index loyalty_ledger_user_idx on public.loyalty_ledger(user_id,created_at desc); create index referral_rewards_status_idx on public.referral_rewards(status,created_at);
create trigger subscription_plans_updated_at before update on public.subscription_plans for each row execute procedure public.set_updated_at(); create trigger catalog_collections_updated_at before update on public.catalog_collections for each row execute procedure public.set_updated_at(); create trigger loyalty_rewards_updated_at before update on public.loyalty_rewards for each row execute procedure public.set_updated_at(); create trigger referral_codes_updated_at before update on public.referral_codes for each row execute procedure public.set_updated_at(); create trigger referral_rewards_updated_at before update on public.referral_rewards for each row execute procedure public.set_updated_at();

alter table public.subscription_plans enable row level security; alter table public.subscription_plan_items enable row level security; alter table public.subscription_charge_attempts enable row level security; alter table public.catalog_collections enable row level security; alter table public.catalog_collection_items enable row level security; alter table public.loyalty_ledger enable row level security; alter table public.loyalty_rewards enable row level security; alter table public.referral_codes enable row level security; alter table public.referral_rewards enable row level security;
create policy "plans_public_read" on public.subscription_plans for select using(is_active or public.is_staff()); create policy "plan_items_public_read" on public.subscription_plan_items for select using(true); create policy "collections_public_read" on public.catalog_collections for select using(is_active and (kind='profile' or (starts_at <= now() and ends_at > now())) or public.is_staff()); create policy "collection_items_public_read" on public.catalog_collection_items for select using(true); create policy "rewards_public_read" on public.loyalty_rewards for select using(is_active or public.is_staff());
create policy "loyalty_owner_read" on public.loyalty_ledger for select using(user_id=auth.uid() or public.is_staff()); create policy "referral_codes_owner" on public.referral_codes for select using(user_id=auth.uid() or public.is_staff()) with check(user_id=auth.uid() or public.is_staff()); create policy "referrals_owner_read" on public.referral_rewards for select using(referred_user_id=auth.uid() or exists(select 1 from public.referral_codes rc where rc.id=referral_code_id and rc.user_id=auth.uid()) or public.is_staff()); create policy "subscription_attempts_owner_read" on public.subscription_charge_attempts for select using(exists(select 1 from public.subscriptions s where s.id=subscription_id and (s.user_id=auth.uid() or public.is_staff())));
create policy "plans_staff_write" on public.subscription_plans for all using(public.is_staff()) with check(public.is_staff()); create policy "plan_items_staff_write" on public.subscription_plan_items for all using(public.is_staff()) with check(public.is_staff()); create policy "collections_staff_write" on public.catalog_collections for all using(public.is_staff()) with check(public.is_staff()); create policy "collection_items_staff_write" on public.catalog_collection_items for all using(public.is_staff()) with check(public.is_staff()); create policy "loyalty_staff_write" on public.loyalty_ledger for all using(public.is_staff()) with check(public.is_staff()); create policy "rewards_staff_write" on public.loyalty_rewards for all using(public.is_staff()) with check(public.is_staff()); create policy "referrals_staff_write" on public.referral_rewards for all using(public.is_staff()) with check(public.is_staff()); create policy "subscription_attempts_staff_write" on public.subscription_charge_attempts for all using(public.is_staff()) with check(public.is_staff());

insert into public.loyalty_rewards(code,name,points_cost,reward_type,discount_percent) values ('OFF5','5% de descuento',50,'discount_percent',5),('FREE_SHIPPING','Envío gratis',100,'free_shipping',null) on conflict(code) do nothing;
